baseURL = 'https://aceberg.github.io/wiki/'
#relativeURLs = false
languageCode = 'en-us'
title = "Aceberg's wiki"
theme = 'hugo-theme-relearn'
enableGitInfo = true

[params]
  alwaysopen = false  # default collapsed sidebar behavior


[menu]
  [[menu.shortcuts]]
    name = '<i class="fa-brands fa-github"></i>&nbsp;&nbsp;GitHub'
    url = 'https://github.com/aceberg'
    weight = 1

[outputs]
  home = ['html', 'rss', 'print']
  page = ['html', 'rss', 'print']
  section = ['html', 'rss', 'print']